on:
    workflow_dispatch: 
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        # - name: initialize
        #   uses: ./.github/actions
        - name: Setup Node.js
          id: setup-node
          uses: actions/setup-node@v4
          with:
            node-version-file: .node-version
            cache: npm
        - name: Install Dependencies
          id: install
          run: npm ci
        - name: Hello world action step
          uses: ./ # Uses an action in the root directory
          id: hello
          with:
            who-to-greet: 'Mona the Octocat'
        - name: Get the output time
          run: echo "The time was ${{ steps.hello.outputs.time }}"
